import { NewsArticle } from './types';

export const SEED_ARTICLES: NewsArticle[] = [
  // --- TOP STORIES (ENGLISH) ---
  {
    id: 'top-en-1',
    hashId: 'isro-gaganyaan-orbital-test',
    title: 'ISRO successfully conducts crucial orbital module test for Gaganyaan human spaceflight mission',
    content: 'The Indian Space Research Organisation (ISRO) on Tuesday successfully carried out the qualification test of the orbital module for its ambitious Gaganyaan human spaceflight programme. The ground test validated propulsion subsystems, thermal controls, and emergency abort sequencing under simulated deep-space conditions. ISRO confirmed all telemetry parameters were nominal, paving the way for uncrewed orbital test flights scheduled later this year.',
    author: 'Vikram Sengupta',
    imageUrl: 'https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?auto=format&fit=crop&w=900&q=80',
    sourceName: 'Press Trust of India (PTI)',
    sourceUrl: 'https://www.isro.gov.in',
    readMoreUrl: 'https://www.isro.gov.in/Gaganyaan.html',
    publishedDate: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 18,
    category: 'top_stories',
    lang: 'en',
    fetchedAt: new Date().toISOString(),
    isTrending: true,
    isBreaking: true,
  },
  {
    id: 'top-en-2',
    hashId: 'rbi-upi-cross-border-expansion',
    title: 'RBI expands UPI international payments framework to six new countries across Southeast Asia',
    content: 'The Reserve Bank of India announced a major expansion of the Unified Payments Interface (UPI) network, linking bilateral instant settlement corridors with central banks across Southeast Asia. Indian travelers and expatriates will now be able to scan native QR codes for seamless merchant payments in local currencies. The central bank stated this initiative marks a watershed moment in the internationalisation of the Indian rupee.',
    author: 'Meera Chidambaram',
    imageUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=900&q=80',
    sourceName: 'LiveMint',
    sourceUrl: 'https://www.livemint.com',
    readMoreUrl: 'https://www.livemint.com/industry/banking/rbi-upi-international-expansion',
    publishedDate: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 45,
    category: 'top_stories',
    lang: 'en',
    fetchedAt: new Date().toISOString(),
    isTrending: true,
  },
  {
    id: 'top-en-3',
    hashId: 'supreme-court-green-corridor-order',
    title: 'Supreme Court directs states to notify dedicated green transit corridors along major expressways',
    content: 'In a landmark environmental ruling, a three-judge bench of the Supreme Court headed by the Chief Justice directed all state governments to establish continuous 500-metre ecological buffer zones and wildlife underpasses along all newly commissioned national expressways. The apex court gave authorities eight weeks to submit compliance roadmaps, stressing that rapid infrastructure development must stay balanced with biodiversity conservation.',
    author: 'Aakash Verma',
    imageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=900&q=80',
    sourceName: 'The Hindu',
    sourceUrl: 'https://www.thehindu.com',
    readMoreUrl: 'https://www.thehindu.com/news/national/sc-verdict-green-corridors',
    publishedDate: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 95,
    category: 'top_stories',
    lang: 'en',
    fetchedAt: new Date().toISOString(),
    isTrending: true,
  },

  // --- NATIONAL / REGIONAL (ENGLISH) ---
  {
    id: 'nat-en-1',
    hashId: 'vande-bharat-sleeper-trains-flagged-off',
    title: 'Indian Railways flags off inaugural commercial run of Vande Bharat Sleeper between New Delhi and Patna',
    content: 'Union Railway Minister flagged off the first commercial journey of the indigenous Vande Bharat Sleeper express on the high-density New Delhi-Patna trunk route. The aerodynamic 16-coach rake features vacuum-assisted bio-toilets, sound-insulated cabins, automated plug doors, and advanced anti-collision Kavach 4.0 safety tech. Travelers lauded the aircraft-like ride quality and 3-hour reduction in overall transit duration.',
    author: 'Pooja Kashyap',
    imageUrl: 'https://images.unsplash.com/photo-1532105956626-9569c03602f6?auto=format&fit=crop&w=900&q=80',
    sourceName: 'Press Trust of India',
    sourceUrl: 'https://www.ptinews.com',
    readMoreUrl: 'https://www.ptinews.com/news/national/vande-bharat-sleeper-patna',
    publishedDate: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 120,
    category: 'national',
    lang: 'en',
    fetchedAt: new Date().toISOString(),
  },
  {
    id: 'nat-en-2',
    hashId: 'delhi-solar-rooftop-policy',
    title: 'Delhi Cabinet approves enhanced subsidy scheme for residential rooftop solar installations',
    content: 'The Delhi government has cleared the comprehensive Solar Energy Policy 2026, offering upfront capital subsidies up to 50% for apartment complexes and individual homeowners installing grid-tied solar panels. The initiative aims to generate 4,500 MW of clean solar power within the capital by 2028, significantly reducing peak summer demand and lowering monthly electricity bills to zero for adhering households.',
    author: 'Rajiv Nambiar',
    imageUrl: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=900&q=80',
    sourceName: 'Hindustan Times Syndicate',
    sourceUrl: 'https://www.hindustantimes.com',
    readMoreUrl: 'https://www.hindustantimes.com/cities/delhi-news/delhi-solar-policy-approval',
    publishedDate: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 150,
    category: 'national',
    lang: 'en',
    fetchedAt: new Date().toISOString(),
  },

  // --- BUSINESS (ENGLISH) ---
  {
    id: 'biz-en-1',
    hashId: 'sensex-nifty-record-high-fii',
    title: 'Sensex scales fresh record high above 82,800 as foreign portfolio inflows accelerate',
    content: 'Benchmark Indian equity indices ended Tuesday at fresh historic peaks, with the 30-share BSE Sensex surging over 450 points to trade above 82,800. Strong buying in banking, IT, and capital goods counters supported the rally alongside robust foreign institutional investor (FII) net purchases of over ₹3,200 crore. Broader midcap and smallcap gauges registered healthy gains as domestic economic indicators stayed resilient.',
    author: 'Devika Nair',
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=900&q=80',
    sourceName: 'Economic Times',
    sourceUrl: 'https://economictimes.indiatimes.com',
    readMoreUrl: 'https://economictimes.indiatimes.com/markets/stocks/news/sensex-nifty-record-highs',
    publishedDate: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 35,
    category: 'business',
    lang: 'en',
    fetchedAt: new Date().toISOString(),
    isTrending: true,
  },
  {
    id: 'biz-en-2',
    hashId: 'india-semiconductor-fabrication-plant',
    title: 'Tata Electronics commences commercial chip packaging tests at Dholera Mega Semiconductor Fab',
    content: 'Tata Electronics has initiated pilot chip validation trials at its multi-billion dollar semiconductor fabrication facility in Dholera, Gujarat. Partnering with Taiwanese technology major PSMC, the mega fab has produced its initial silicon wafers across 28nm and 40nm nodes designated for automotive, power electronics, and industrial microcontrollers. Union IT Minister termed the development a historic milestone toward technological self-reliance.',
    author: 'Sunil Rao',
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80',
    sourceName: 'Business Standard',
    sourceUrl: 'https://www.business-standard.com',
    readMoreUrl: 'https://www.business-standard.com/companies/news/tata-dholera-semiconductor-trials',
    publishedDate: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 180,
    category: 'business',
    lang: 'en',
    fetchedAt: new Date().toISOString(),
  },

  // --- SPORTS (ENGLISH) ---
  {
    id: 'spt-en-1',
    hashId: 'bcci-test-squad-announcement',
    title: 'BCCI announces 16-member Test squad: Rishabh Pant named vice-captain, young pacer earns maiden call-up',
    content: 'The Senior Men’s Selection Committee of the BCCI announced a formidable 16-member squad for the upcoming three-match home Test series. Wicketkeeper-batter Rishabh Pant has been formally elevated to vice-captaincy following his stellar domestic recovery form. Promising left-arm speedster from Bengal earned his maiden Test cap after a record-breaking 42-wicket Ranji Trophy season.',
    author: 'Karan Mehra',
    imageUrl: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=900&q=80',
    sourceName: 'ESPNcricinfo',
    sourceUrl: 'https://www.espncricinfo.com',
    readMoreUrl: 'https://www.espncricinfo.com/series/india-home-test-squad',
    publishedDate: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 60,
    category: 'sports',
    lang: 'en',
    fetchedAt: new Date().toISOString(),
    isTrending: true,
  },
  {
    id: 'spt-en-2',
    hashId: 'neeraj-chopra-diamond-league-gold',
    title: 'Neeraj Chopra clinches Gold at Brussels Diamond League final with monstrous 89.45m javelin throw',
    content: 'Olympic champion Neeraj Chopra produced a masterclass on his fifth attempt to capture the prestigious Diamond League Trophy in Brussels. Competing against reigning world champion Julian Weber and Anderson Peters, Chopra unleashed a mammoth 89.45-metre throw in the penultimate round. Neeraj dedicated the triumph to young athletics academy trainees across rural Haryana and Punjab.',
    author: 'Tanvi Shirodkar',
    imageUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=900&q=80',
    sourceName: 'Sportstar',
    sourceUrl: 'https://sportstar.thehindu.com',
    readMoreUrl: 'https://sportstar.thehindu.com/athletics/neeraj-chopra-brussels-diamond-league-victory',
    publishedDate: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 240,
    category: 'sports',
    lang: 'en',
    fetchedAt: new Date().toISOString(),
  },

  // --- WORLD (ENGLISH) ---
  {
    id: 'wld-en-1',
    hashId: 'un-climate-summit-loss-and-damage',
    title: 'UN Climate Summit achieves historic consensus on $100 billion annual climate resilience fund for Global South',
    content: 'Negotiators from over 190 member nations at the United Nations Climate Assembly finalized operational modalities for a permanent $100 billion annual climate loss-and-damage trust fund. The fund will disburse low-interest green transition capital and emergency reconstruction grants to developing countries facing severe climate hazards. India welcomed the pact as a major victory for equitable climate justice.',
    author: 'Arjun Das',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=900&q=80',
    sourceName: 'Reuters',
    sourceUrl: 'https://www.reuters.com',
    readMoreUrl: 'https://www.reuters.com/world/un-climate-fund-consensus',
    publishedDate: new Date(Date.now() - 1000 * 60 * 110).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 110,
    category: 'world',
    lang: 'en',
    fetchedAt: new Date().toISOString(),
  },

  // --- TECHNOLOGY (ENGLISH) ---
  {
    id: 'tech-en-1',
    hashId: 'bhashini-ai-multilingual-speech',
    title: 'Digital India Bhashini deploys real-time conversational voice AI supporting 22 Indian regional dialects',
    content: 'India’s national language technology mission, Bhashini, released an advanced open neural voice translation stack capable of zero-latency speech synthesis across 22 scheduled Indian languages and 75 regional dialects. Integrated into state citizen welfare portals, the voice assistant enables non-English speaking rural citizens to access land records, pension schemes, and crop insurance through natural voice commands on standard mobile phones.',
    author: 'Neha Deshmukh',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=900&q=80',
    sourceName: 'TechCircle India',
    sourceUrl: 'https://www.techcircle.in',
    readMoreUrl: 'https://www.techcircle.in/2026/09/bhashini-multilingual-voice-ai-rollout',
    publishedDate: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 75,
    category: 'technology',
    lang: 'en',
    fetchedAt: new Date().toISOString(),
    isTrending: true,
  },
  {
    id: 'tech-en-2',
    hashId: 'ola-tvs-solid-state-ev-batteries',
    title: 'Indian EV manufacturers begin indigenous testing of high-energy-density solid-state battery cells',
    content: 'Leading Indian two-wheeler electric mobility companies have kicked off on-road endurance tests for first-generation solid-state lithium cells developed in collaboration with premier IIT labs. The new chemistry provides 40% higher volumetric energy density, eliminates fire hazards under extreme 50°C Indian summer ambient conditions, and enables rapid 15-minute fast charging to 80% capacity.',
    author: 'Rohit Kulkarni',
    imageUrl: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=900&q=80',
    sourceName: 'Autocar India',
    sourceUrl: 'https://www.autocarindia.com',
    readMoreUrl: 'https://www.autocarindia.com/ev-news/solid-state-battery-trials-india',
    publishedDate: new Date(Date.now() - 1000 * 60 * 210).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 210,
    category: 'technology',
    lang: 'en',
    fetchedAt: new Date().toISOString(),
  },

  // --- ENTERTAINMENT (ENGLISH) ---
  {
    id: 'ent-en-1',
    hashId: 'national-film-awards-winners-announced',
    title: '71st National Film Awards: Dynamic indie cinema sweeps top honors; legendary composer honored with Dadasaheb Phalke',
    content: 'The Ministry of Information and Broadcasting announced the winners of the 71st National Film Awards in the capital. Groundbreaking independent regional features in Malayalam, Kannada, and Marathi dominated best feature and screenplay categories. Legendary music maestro received the prestigious Dadasaheb Phalke Award for five decades of transformative contributions to Indian classical and cinematic orchestration.',
    author: 'Shalini Kapoor',
    imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=900&q=80',
    sourceName: 'Filmfare',
    sourceUrl: 'https://www.filmfare.com',
    readMoreUrl: 'https://www.filmfare.com/news/national-film-awards-full-winners-list',
    publishedDate: new Date(Date.now() - 1000 * 60 * 130).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 130,
    category: 'entertainment',
    lang: 'en',
    fetchedAt: new Date().toISOString(),
  },

  // --- SCIENCE (ENGLISH) ---
  {
    id: 'sci-en-1',
    hashId: 'ladakh-highest-gamma-ray-telescope',
    title: 'Asia’s highest gamma-ray observatory operationalized at Hanle in Ladakh at 4,300 metres altitude',
    content: 'Indian astrophysicists have formally commissioned the Major Atmospheric Cherenkov Experiment (MACE) telescope at Hanle, high in eastern Ladakh. Standing 4,300 metres above sea level, it represents the second largest gamma-ray telescope worldwide. The high-altitude observatory will scan distant supermassive black holes, active galactic nuclei, and cosmic ray acceleration zones with unprecedented sensitivity and spectral resolution.',
    author: 'Dr. Siddharth Roy',
    imageUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=900&q=80',
    sourceName: 'Department of Atomic Energy',
    sourceUrl: 'https://dae.gov.in',
    readMoreUrl: 'https://dae.gov.in/mace-telescope-hanle-ladakh-commissioned',
    publishedDate: new Date(Date.now() - 1000 * 60 * 280).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 280,
    category: 'science',
    lang: 'en',
    fetchedAt: new Date().toISOString(),
  },

  // --- MISCELLANEOUS / HATKE (ENGLISH) ---
  {
    id: 'misc-en-1',
    hashId: 'bengaluru-engineer-plants-urban-forest',
    title: 'Bengaluru techie transforms barren 4-acre quarry into lush self-sustaining Miyawaki mini-forest',
    content: 'Using the Japanese Miyawaki intensive plantation technique, a 34-year-old software architect from Whitefield successfully regenerated a four-acre abandoned granite quarry on Bengaluru’s outskirts. In less than 30 months, over 14,000 native saplings grew into a thriving canopy, bringing groundwater levels up by 25 feet and attracting over 60 bird and butterfly species to the previously dry wasteland.',
    author: 'Ananya Hegde',
    imageUrl: 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?auto=format&fit=crop&w=900&q=80',
    sourceName: 'The Better India',
    sourceUrl: 'https://www.thebetterindia.com',
    readMoreUrl: 'https://www.thebetterindia.com/bengaluru-techie-miyawaki-quarry-forest',
    publishedDate: new Date(Date.now() - 1000 * 60 * 320).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 320,
    category: 'miscellaneous',
    lang: 'en',
    fetchedAt: new Date().toISOString(),
  },

  // ==========================================
  // --- HINDI (हिंदी) SEED ARTICLES ---
  // ==========================================
  {
    id: 'top-hi-1',
    hashId: 'isro-gaganyaan-hindi-orbital',
    title: 'गगनयान मिशन: इसरो ने ऑर्बिटल मॉड्यूल का सफल परीक्षण किया, अंतरिक्ष यात्रियों की सुरक्षा परखी',
    content: 'भारतीय अंतरिक्ष अनुसंधान संगठन (इसरो) ने मंगलवार को अपने महत्वाकांक्षी मानव अंतरिक्ष उड़ान कार्यक्रम ‘गगनयान’ के ऑर्बिटल मॉड्यूल का सफल परीक्षण पूरा किया। इस ग्राउंड टेस्ट में प्रणोदन प्रणाली, थर्मल नियंत्रण और आपातकालीन एबॉर्ट व्यवस्था की गहन जांच की गई। इसरो ने बताया कि सभी मानक पूरी तरह सामान्य पाए गए हैं, जिससे आगामी मानवरहित परीक्षण उड़ानों का मार्ग प्रशस्त हुआ है।',
    author: 'विक्रम सेनगुप्ता',
    imageUrl: 'https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?auto=format&fit=crop&w=900&q=80',
    sourceName: 'प्रेस ट्रस्ट ऑफ इंडिया (भाषा)',
    sourceUrl: 'https://www.isro.gov.in',
    readMoreUrl: 'https://www.isro.gov.in/Gaganyaan.html',
    publishedDate: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 20,
    category: 'top_stories',
    lang: 'hi',
    fetchedAt: new Date().toISOString(),
    isTrending: true,
    isBreaking: true,
  },
  {
    id: 'top-hi-2',
    hashId: 'upi-international-expansion-hindi',
    title: 'आरबीआई ने यूपीआई का दायरा बढ़ाया: अब दक्षिण पूर्व एशिया के छह देशों में चलेगा भारतीय क्यूआर कोड',
    content: 'भारतीय रिजर्व बैंक ने यूनिफाइड पेमेंट्स इंटरफेस (यूपीआई) नेटवर्क का विस्तार करते हुए दक्षिण पूर्व एशिया के छह देशों के केंद्रीय बैंकों के साथ त्वरित भुगतान गलियारे शुरू किए हैं। अब भारतीय पर्यटक और प्रवासी नागरिक बिना किसी विदेशी मुद्रा कार्ड के सीधे स्थानीय क्यूआर कोड स्कैन करके भारतीय रुपयों में भुगतान कर सकेंगे। इसे भारतीय मुद्रा के अंतर्राष्ट्रीयकरण में बड़ा कदम बताया जा रहा है।',
    author: 'मीरा चिदंबरम',
    imageUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=900&q=80',
    sourceName: 'लाइवमिंट हिंदी',
    sourceUrl: 'https://www.livemint.com',
    readMoreUrl: 'https://www.livemint.com/industry/banking/rbi-upi-international-expansion',
    publishedDate: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 50,
    category: 'top_stories',
    lang: 'hi',
    fetchedAt: new Date().toISOString(),
    isTrending: true,
  },
  {
    id: 'biz-hi-1',
    hashId: 'sensex-record-high-hindi',
    title: 'सेंसेक्स 82,800 के ऐतिहासिक शिखर पर बंद, विदेशी निवेशकों की भारी लिवाली से बाजार में तेजी',
    content: 'भारतीय शेयर बाजार ने मंगलवार को नया रिकॉर्ड बनाया। बॉम्बे स्टॉक एक्सचेंज का 30 शेयरों वाला संवेदी सूचकांक सेंसेक्स 450 अंक से अधिक उछलकर 82,800 के पार बंद हुआ। बैंकिंग, आईटी और ऑटो शेयरों में जोरदार खरीदारी देखने को मिली। विदेशी संस्थागत निवेशकों ने 3,200 करोड़ रुपये से अधिक की शुद्ध लिवाली की, जिससे निफ्टी भी 25,200 के नए ऑल-टाइम हाई स्तर पर पहुंच गया।',
    author: 'देविका नायर',
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=900&q=80',
    sourceName: 'इकोनॉमिक टाइम्स',
    sourceUrl: 'https://economictimes.indiatimes.com',
    readMoreUrl: 'https://economictimes.indiatimes.com/markets/stocks/news/sensex-nifty-record-highs',
    publishedDate: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 40,
    category: 'business',
    lang: 'hi',
    fetchedAt: new Date().toISOString(),
    isTrending: true,
  },
  {
    id: 'spt-hi-1',
    hashId: 'bcci-squad-hindi',
    title: 'टेस्ट सीरीज के लिए टीम इंडिया का ऐलान: ऋषभ पंत बने उपकप्तान, नए तेज गेंदबाज को मिला मौका',
    content: 'बीसीसीआई की चयन समिति ने घरेलू तीन टेस्ट मैचों की श्रृंखला के लिए 16 सदस्यीय भारतीय टीम की घोषणा कर दी है। विकेटकीपर-बल्लेबाज ऋषभ पंत को शानदार फॉर्म के बाद औपचारिक रूप से उपकप्तानी सौंपी गई है। वहीं, रणजी ट्रॉफी में 42 विकेट चटकाने वाले बंगाल के युवा बाएं हाथ के तेज गेंदबाज को पहली बार भारतीय टेस्ट टीम में शामिल किया गया है।',
    author: 'करण मेहरा',
    imageUrl: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=900&q=80',
    sourceName: 'ईएसपीएन क्रिकइन्फो',
    sourceUrl: 'https://www.espncricinfo.com',
    readMoreUrl: 'https://www.espncricinfo.com/series/india-home-test-squad',
    publishedDate: new Date(Date.now() - 1000 * 60 * 65).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 65,
    category: 'sports',
    lang: 'hi',
    fetchedAt: new Date().toISOString(),
    isTrending: true,
  },
  {
    id: 'nat-hi-1',
    hashId: 'vande-bharat-sleeper-hindi',
    title: 'नई दिल्ली-पटना वंदे भारत स्लीपर ट्रेन को हरी झंडी, आधुनिक सुविधाओं से लैस है 16 कोच वाली ट्रेन',
    content: 'रेल मंत्री ने नई दिल्ली से पटना के बीच पहली स्वदेशी वंदे भारत स्लीपर ट्रेन को हरी झंडी दिखाकर रवाना किया। यह ट्रेन अत्याधुनिक वैक्यूम टॉयलेट्स, एयरक्राफ्ट जैसी शांत यात्रा व्यवस्था और कवच 4.0 सुरक्षा प्रणाली से लैस है। 16 कोच वाली इस ट्रेन से दोनों प्रमुख राजधानियों के बीच यात्रा के समय में लगभग 3 घंटे की भारी कमी दर्ज की गई है।',
    author: 'पूजा कश्यप',
    imageUrl: 'https://images.unsplash.com/photo-1532105956626-9569c03602f6?auto=format&fit=crop&w=900&q=80',
    sourceName: 'पीटीआई भाषा',
    sourceUrl: 'https://www.ptinews.com',
    readMoreUrl: 'https://www.ptinews.com/news/national/vande-bharat-sleeper-patna',
    publishedDate: new Date(Date.now() - 1000 * 60 * 125).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 125,
    category: 'national',
    lang: 'hi',
    fetchedAt: new Date().toISOString(),
  },
  {
    id: 'tech-hi-1',
    hashId: 'bhashini-ai-voice-hindi',
    title: 'डिजिटल इंडिया भाषिणी ने 22 भारतीय भाषाओं में रीयल-टाइम वॉइस ट्रांसलेशन एआई पेश किया',
    content: 'राष्ट्रीय भाषा प्रौद्योगिकी मिशन ‘भाषिणी’ ने बिना किसी रुकावट के काम करने वाला न्यूरल वॉइस ट्रांसलेशन सिस्टम जारी किया है, जो 22 भारतीय भाषाओं और 75 बोलियों को समझता है। सरकारी कल्याणकारी पोर्टलों से जुड़े इस वॉइस असिस्टेंट की मदद से ग्रामीण नागरिक अपनी स्थानीय बोली में बोलकर जमीन के दस्तावेज, पेंशन और फसल बीमा की जानकारी फोन पर ही प्राप्त कर सकेंगे।',
    author: 'नेहा देशमुख',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=900&q=80',
    sourceName: 'टेक सर्कल भारत',
    sourceUrl: 'https://www.techcircle.in',
    readMoreUrl: 'https://www.techcircle.in/2026/09/bhashini-multilingual-voice-ai-rollout',
    publishedDate: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 80,
    category: 'technology',
    lang: 'hi',
    fetchedAt: new Date().toISOString(),
    isTrending: true,
  },
  {
    id: 'wld-hi-1',
    hashId: 'un-climate-summit-hindi',
    title: 'संयुक्त राष्ट्र जलवायु सम्मेलन: विकासशील देशों के लिए 100 अरब डॉलर के कोष पर बनी वैश्विक सहमति',
    content: 'संयुक्त राष्ट्र जलवायु सम्मेलन में 190 से अधिक सदस्य देशों के प्रतिनिधियों ने जलवायु परिवर्तन से होने वाले नुकसान की भरपाई के लिए 100 अरब डॉलर के वार्षिक ट्रस्ट फंड को अंतिम रूप दिया। इस फंड के जरिए प्राकृतिक आपदाओं से जूझ रहे देशों को बिना किसी कठोर शर्त के पुनर्निर्माण अनुदान मिलेगा। भारत ने इस ऐतिहासिक समझौते का स्वागत करते हुए इसे विकासशील देशों की जीत बताया।',
    author: 'अर्जुन दास',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=900&q=80',
    sourceName: 'रॉयटर्स हिंदी',
    sourceUrl: 'https://www.reuters.com',
    readMoreUrl: 'https://www.reuters.com/world/un-climate-fund-consensus',
    publishedDate: new Date(Date.now() - 1000 * 60 * 115).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 115,
    category: 'world',
    lang: 'hi',
    fetchedAt: new Date().toISOString(),
  },
  {
    id: 'ent-hi-1',
    hashId: 'national-film-awards-hindi',
    title: '71वें राष्ट्रीय फिल्म पुरस्कार: क्षेत्रीय सिनेमा का दबदबा, दिग्गज संगीतकार को दादा साहब फाल्के पुरस्कार',
    content: 'सूचना एवं प्रसारण मंत्रालय ने नई दिल्ली में 71वें राष्ट्रीय फिल्म पुरस्कारों की घोषणा की। इस बार क्षेत्रीय सिनेमा, विशेषकर मलयालम, कन्नड़ और मराठी फिल्मों ने सर्वश्रेष्ठ पटकथा और फीचर फिल्म श्रेणियों में अपना परचम लहराया। भारतीय संगीत में पांच दशकों के अमूल्य योगदान के लिए दिग्गज संगीतकार को प्रतिष्ठित दादा साहब फाल्के पुरस्कार से सम्मानित किया गया।',
    author: 'शालिनी कपूर',
    imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=900&q=80',
    sourceName: 'फिल्मफेयर',
    sourceUrl: 'https://www.filmfare.com',
    readMoreUrl: 'https://www.filmfare.com/news/national-film-awards-full-winners-list',
    publishedDate: new Date(Date.now() - 1000 * 60 * 135).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 135,
    category: 'entertainment',
    lang: 'hi',
    fetchedAt: new Date().toISOString(),
  },
  {
    id: 'sci-hi-1',
    hashId: 'hanle-ladakh-telescope-hindi',
    title: 'लद्दाख के हानले में 4,300 मीटर की ऊंचाई पर शुरू हुई एशिया की सबसे ऊंची गामा-रे वेधशाला',
    content: 'भारतीय खगोल भौतिकविदों ने पूर्वी लद्दाख के हानले में अत्याधुनिक मेजर एटमॉस्फेरिक चेरेनकोव एक्सपेरिमेंट (MACE) टेलीस्कोप चालू कर दिया है। समुद्र तल से 4,300 मीटर की ऊंचाई पर स्थित यह वेधशाला दुनिया की दूसरी सबसे बड़ी गामा-रे दूरबीन है। यह अत्यंत संवेदनशील वेधशाला दूरस्थ ब्लैक होल्स, सुपरनोवा और ब्रह्मांडीय किरणों के स्रोतों का अध्ययन करने में सक्षम होगी।',
    author: 'डॉ. सिद्धार्थ रॉय',
    imageUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=900&q=80',
    sourceName: 'परमाणु ऊर्जा विभाग',
    sourceUrl: 'https://dae.gov.in',
    readMoreUrl: 'https://dae.gov.in/mace-telescope-hanle-ladakh-commissioned',
    publishedDate: new Date(Date.now() - 1000 * 60 * 285).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 285,
    category: 'science',
    lang: 'hi',
    fetchedAt: new Date().toISOString(),
  },
  {
    id: 'misc-hi-1',
    hashId: 'bengaluru-urban-forest-hindi',
    title: 'बेंगलुरु के इंजीनियर ने बंजर खदान को 14,000 पेड़ लगाकर बनाया हरा-भरा मियावाकी जंगल',
    content: 'बेंगलुरु के एक 34 वर्षीय सॉफ्टवेयर आर्किटेक्ट ने जापानी मियावाकी पद्धति का उपयोग करके शहर के बाहरी इलाके में स्थित एक बंजर ग्रेनाइट खदान को घने जंगल में बदल दिया है। केवल ढाई साल में 14,000 से अधिक देसी पौधे बड़े पेड़ बन गए हैं, जिससे इलाके का भूजल स्तर 25 फीट ऊपर आ गया है और यहां 60 से अधिक प्रजातियों के पक्षी और तितलियां लौट आए हैं।',
    author: 'अनन्या हेगड़े',
    imageUrl: 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?auto=format&fit=crop&w=900&q=80',
    sourceName: 'द बेटर इंडिया हिंदी',
    sourceUrl: 'https://www.thebetterindia.com',
    readMoreUrl: 'https://www.thebetterindia.com/bengaluru-techie-miyawaki-quarry-forest',
    publishedDate: new Date(Date.now() - 1000 * 60 * 325).toISOString(),
    publishedTimestamp: Date.now() - 1000 * 60 * 325,
    category: 'miscellaneous',
    lang: 'hi',
    fetchedAt: new Date().toISOString(),
  },
];
